package it.italiaonline.rnd

import groovy.util.logging.Slf4j

/**
 * This Groovy source file was auto generated by 'gigawatt'
 * @author gsus
 * @date 10-03-2017 10.46
 */
@Slf4j
class GZipEngine {
	/**
	 * This method returns always true.
	 */
	Boolean someGZipEngineMethod() {
		true
	}
}
